# Generated by Django 4.1.5 on 2023-01-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
